name: mdbook_utils_ci
services:
  mdbook-utils:
    image: mdbook_utils_ci:${IMAGE_VERSION}  # Name and tag of the image that will be built
    build:
      target: ci
      cache_from:
        - type=gha                           # GitHub Action cache
        #- type=local,dest=./.cache
      cache_to:
        - type=gha,mode=max
        #- type=local,dest=./.cache
    volumes:
      - /userguide:/code/userguide/book/
