on:
  #push:
    # Pattern matched against refs/tags
    #tags:
    #  - '*'           # Push events to every tag not containing /
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Basic information
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event from @${{ github.actor }}. The OS is ${{ runner.os }}"
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker compose -f .devcontainer/compose.yaml -f .devcontainer/compose-ci.yaml build
      - name: Build the code
        run: docker compose -f .devcontainer/compose.yaml -f .devcontainer/compose-ci.yaml run mdbook-utils
      # - run: cargo publish --token ${CRATES_TOKEN}
      #   env:
      #     CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
